### PR TITLE
Move to Vagrant to control deployments to Virtualbox or AWS

### PR DESCRIPTION
**Pull request by grenzr**
Hope this simplifies the deployment for either target now :)

### CODE REVIEW

**Comment by grenzr** [comment]
Still got issues here. Use of 1504/1510 both result in this: https://github.com/concourse/bin/issues/14 .. Using trusty64 with vivid kernel works, but need to get the ansible wait for reboot working before installing concourse.

**Comment by grenzr** [comment]
OK - this should work in Virtualbox now. About to test in AWS.

**Comment by grenzr** [comment]
Yep, works in AWS. Would be good to have some test-kitchen behind this too, but its ready to merge in current state.

**Comment by anorsich** [comment]
@grenzr Great job! I am going to merge it right after I finish that comment. 
The only concern I have is that now we use vagrant to setup and deploy things. That does not cover  cases when users just have Linux machine out there and have ssh access to it.  In that case, we just need to be able to run ansible playbooks without vagrant. I might be missing something since I do not have a lot of experience using vagrant for provisioning cloud servers. Typically I just use Ansible for deployment and vagrant for development  (Docker is more often now).

Merging now 👍

**Comment by grenzr** [comment]
Its a fair point. You can still run this without Vagrant as you did before.
While I was fixing the Ansible scripts and rebuilding the machine in AWS/Virtualbox I found it laborious manually destroying/creating the machine to test it, so I setup a Vagrantfile to automate that process better.
Perhaps the README could be updated to include if you wish to run this without Vagrant, but its definately still possible as it was before.

Thanks for merging though :)

**Pull request merged**
